# Generated by Django 4.0.5 on 2022-06-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('Users_assets', '0003_alter_user_tg_id_alter_usertag_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_id', models.CharField(max_length=50, verbose_name='ID рассылки')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Рассылка создана')),
                ('sending_time', models.DateTimeField(verbose_name='Время рассылки')),
                ('sending_text', models.TextField(verbose_name='Текст рассылки')),
                ('send_done', models.BooleanField(default=False, verbose_name='Рассылка исполнена')),
                ('report', models.TextField(blank=True, default='', null=True, verbose_name='Отчёт по произведённой рассылке')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users_assets.user', verbose_name='Создатель рассылки')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='bot', to='core.tgbot', verbose_name='Через бота')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='Время сообщения')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Ответ бота')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='bot', to='core.tgbot', verbose_name='Через бота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users_assets.user', verbose_name='Создатель рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'История сообщений',
            },
        ),
    ]
