# Generated by Django 4.0.1 on 2022-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_config',
            name='ssl_cert',
            field=models.CharField(default='/etc/letsencrypt/live/insiderlab.ru/fullchain.pem', max_length=100, verbose_name='Path to the ssl certificate'),
        ),
        migrations.AlterField(
            model_name='bot_config',
            name='ssl_private',
            field=models.CharField(default='/etc/letsencrypt/live/insiderlab.ru/privkey.pem', max_length=100, verbose_name='Path to the ssl private key'),
        ),
        migrations.AlterField(
            model_name='bot_config',
            name='webhook_url_path',
            field=models.CharField(default='/bothook', max_length=100, verbose_name='URL path'),
        ),
    ]
