# Generated by Django 4.0.1 on 2022-02-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_user_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='tg_ID',
        ),
    ]
