# Generated by Django 4.0.1 on 2022-02-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_rename_id_user_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_name', models.CharField(max_length=150, verbose_name='ФИО полностью')),
                ('rsi_id', models.CharField(max_length=50, verbose_name='RSI ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('club_status', models.CharField(max_length=50, verbose_name='Клубный статус')),
                ('exp_date', models.DateField(verbose_name='Дата окончания подписки')),
                ('active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.user', verbose_name='Подписчик телеграм')),
            ],
        ),
    ]
