# Generated by Django 4.0.1 on 2022-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ref_code',
            field=models.CharField(default='markschool', max_length=10, verbose_name='Реферальный код'),
        ),
    ]
