# Generated by Django 4.0.1 on 2022-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_alter_partner_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='ref_code',
            field=models.CharField(default='markschool', editable=False, max_length=10, unique=True, verbose_name='Реферальный код'),
        ),
    ]
