# Generated by Django 4.0.1 on 2022-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_alter_partner_ref_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new_group', max_length=50, verbose_name='Название переменной для группы (латиницей)')),
                ('caption', models.CharField(default='Новая группа', max_length=50, verbose_name='Отображаемое наименование группы')),
                ('g_type', models.CharField(choices=[('local', 'Локальная группа'), ('global', 'Глобальная группа')], default='global', max_length=10, verbose_name='Тип группы')),
                ('users', models.ManyToManyField(to='webhook.User', verbose_name='Члены группы')),
            ],
        ),
    ]
