# Generated by Django 4.0.1 on 2022-02-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_config',
            name='bot_url',
            field=models.CharField(default='', max_length=50, verbose_name='Bot link'),
        ),
    ]
