# Generated by Django 4.0.1 on 2022-02-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0011_bot_config_bot_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_caption', models.CharField(max_length=128)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='webhook.user')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='webhook.partner')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
