# Generated by Django 4.0.1 on 2022-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0012_reflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_ref_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
