# Generated by Django 4.0.1 on 2022-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0013_user_parent_ref_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot_config',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Телеграм боты'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='reflink',
            options={'verbose_name': 'Реферальная связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Группа людей', 'verbose_name_plural': 'Группы людей'},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
