# Generated by Django 4.0.1 on 2022-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0014_alter_bot_config_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_profile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('age_cat', models.CharField(max_length=10, verbose_name='Возростная категория')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('invest_value', models.FloatField(default=0, verbose_name='Инвестиционный капитал')),
                ('business_expirience', models.CharField(max_length=150, verbose_name='Опыт предпринимательства')),
            ],
        ),
    ]
