# Generated by Django 4.0.1 on 2022-03-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0015_usr_profile_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usr_profile_data',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Дополнительная информация о пользователях'},
        ),
    ]
