# Generated by Django 4.0.1 on 2022-03-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0017_user_ping_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.usr_profile_data', verbose_name='Дополнительная информация'),
        ),
    ]
