# Generated by Django 4.0.1 on 2022-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0019_alter_usr_profile_data_invest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_profile_data',
            name='age_cat',
            field=models.CharField(max_length=20, verbose_name='Возростная категория'),
        ),
    ]
