# Generated by Django 4.0.1 on 2022-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0020_alter_usr_profile_data_age_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_profile_data',
            name='invest_value',
            field=models.CharField(max_length=100, verbose_name='Инвестиционный капитал'),
        ),
    ]
