# Generated by Django 4.0.1 on 2022-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0021_alter_usr_profile_data_invest_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_profile_data',
            name='age_cat',
            field=models.CharField(choices=[('18-', 'до 18 лет'), ('18-24', 'от 18 до 24 лет'), ('25-30', 'от 25 до 30 лет'), ('31-40', 'от 31 до 40 лет'), ('41-50', 'от 41 до 50 лет'), ('50+', 'старше 50 лет')], max_length=20, verbose_name='Возростная категория'),
        ),
        migrations.AlterField(
            model_name='usr_profile_data',
            name='business_expirience',
            field=models.CharField(choices=[('Not_realy', 'Нет, всегда работал в найме'), ('Freelance', 'Работал сам на себя, самостоятельно'), ('Have_a_lot', 'Да, есть опыт бизнеса с наёмным персоналом')], max_length=150, verbose_name='Опыт предпринимательства'),
        ),
        migrations.AlterField(
            model_name='usr_profile_data',
            name='invest_value',
            field=models.CharField(choices=[('1000-', 'Да, до $1000'), ('1000+', 'Да, от $1000 до $5000'), ('5000+', 'Да, от $5000 до $15000'), ('15000+', 'Да, от $15,000 до $100,000'), ('100000+', 'Да, свыше $100,000'), ('No investments', 'Нет, начинаю с чистого листа')], max_length=100, verbose_name='Инвестиционный капитал'),
        ),
    ]
