# Generated by Django 4.0.1 on 2022-03-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0023_usr_profile_data_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr_profile_data',
            name='button',
        ),
    ]
