# Generated by Django 4.0.1 on 2022-03-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0024_alter_keyboard_buttons'),
        ('webhook', '0024_remove_usr_profile_data_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr_profile_data',
            name='age_cat_b',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyboard__name': 'age_category_choise_kb'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age', to='bot_content.keyboard_button', verbose_name='Возростная категория'),
        ),
        migrations.AddField(
            model_name='usr_profile_data',
            name='business_expirience_b',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyboard__name': 'business_expirience_kb'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='bot_content.keyboard_button', verbose_name='Опыт предпринимательства'),
        ),
        migrations.AddField(
            model_name='usr_profile_data',
            name='invest_value_b',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyboard__name': 'invest_value_kb'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invest', to='bot_content.keyboard_button', verbose_name='Инвестиционный капитал'),
        ),
    ]
