# Generated by Django 4.0.1 on 2022-03-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0025_usr_profile_data_age_cat_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr_profile_data',
            name='age_cat',
        ),
        migrations.RemoveField(
            model_name='usr_profile_data',
            name='business_expirience',
        ),
        migrations.RemoveField(
            model_name='usr_profile_data',
            name='invest_value',
        ),
    ]
