# Generated by Django 4.0.1 on 2022-03-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0024_alter_keyboard_buttons'),
        ('webhook', '0026_remove_usr_profile_data_age_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='buttons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_content.keyboard_button', verbose_name='По каким кнопкам добавлять в группу'),
        ),
    ]
