# Generated by Django 4.0.1 on 2022-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0024_alter_keyboard_buttons'),
        ('webhook', '0028_remove_usergroup_buttons_usergroup_buttons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='buttons',
            field=models.ManyToManyField(blank=True, related_name='group_additing', to='bot_content.keyboard_button', verbose_name='По каким кнопкам добавлять в группу'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(blank=True, to='webhook.User', verbose_name='Члены группы'),
        ),
    ]
