# Generated by Django 4.0.5 on 2022-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True, verbose_name='Имя переменной (только латиница)')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание переменной')),
                ('value', models.CharField(max_length=200, verbose_name='Значение переменной')),
            ],
            options={
                'verbose_name': 'Переменная окружения',
                'verbose_name_plural': 'Переменные окружения',
            },
        ),
        migrations.CreateModel(
            name='TgBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True, verbose_name='Наименование бота')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('url', models.CharField(max_length=150, verbose_name='Ссылка на бота')),
                ('token', models.CharField(max_length=150, verbose_name='API token телеграм бота')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Телеграм боты',
            },
        ),
    ]
