# Generated by Django 4.0.4 on 2022-04-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование бота')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('url', models.CharField(max_length=150, verbose_name='Ссылка на бота')),
                ('token', models.CharField(max_length=150, verbose_name='API token телеграм бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Телеграм боты',
            },
        ),
        migrations.RenameModel(
            old_name='EnvVars',
            new_name='EnvVar',
        ),
    ]
