# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgbot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgbot',
            name='first_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение при первом касании "/start"'),
        ),
        migrations.AlterField(
            model_name='tgbot',
            name='caption',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование бота'),
        ),
    ]
