# Generated by Django 4.0.4 on 2022-05-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tgbot_first_message_alter_tgbot_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgbot',
            name='first_message',
        ),
    ]
