# Generated by Django 4.0.4 on 2022-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tgbot_first_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgbot',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
