# Generated by Django 4.0.1 on 2022-02-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_content', '0015_delete_typical_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='typical_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('caption', models.CharField(max_length=50, verbose_name='Назавание блока')),
                ('block_id', models.CharField(max_length=50, unique=True, verbose_name='ID блока')),
                ('text', models.TextField(verbose_name='Содержание сообщения')),
                ('from_button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard_button', verbose_name='По какой кнопке появиться')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard', verbose_name='Клавиатура')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.state', verbose_name='Штатная позиция')),
            ],
        ),
    ]
