# Generated by Django 4.0.1 on 2022-02-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('text', models.CharField(max_length=50, verbose_name='Текст команды')),
                ('go_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_logic.typical_block', verbose_name='Вызываемый блок')),
            ],
        ),
    ]
