# Generated by Django 4.0.1 on 2022-02-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0017_remove_main_menu_reaction_start_business'),
        ('bot_logic', '0003_rename_text_commands_text_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typical_block',
            name='from_button',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard_button', verbose_name='По какой кнопке появиться'),
        ),
    ]
