# Generated by Django 4.0.1 on 2022-02-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0021_alter_keyboard_button_visibls_for'),
        ('bot_logic', '0004_alter_typical_block_from_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='typical_block',
            name='input_data',
            field=models.BooleanField(default=False, verbose_name='Фиксировать введённые данные?'),
        ),
        migrations.AlterField(
            model_name='typical_block',
            name='from_button',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard_button', verbose_name='По какой кнопке появиться'),
        ),
        migrations.AlterField(
            model_name='typical_block',
            name='kb',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard', verbose_name='Клавиатура'),
        ),
    ]
