# Generated by Django 4.0.1 on 2022-02-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0005_typical_block_input_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typical_block',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_logic.typical_block'),
        ),
    ]
