# Generated by Django 4.0.1 on 2022-03-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0007_alter_typical_block_from_button_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text_command',
            options={'verbose_name': 'Текстовая команда', 'verbose_name_plural': 'Текстовые команды'},
        ),
        migrations.AlterModelOptions(
            name='typical_block',
            options={'verbose_name': 'Типовой блок сообщения', 'verbose_name_plural': 'Типовые блоки'},
        ),
    ]
