# Generated by Django 4.0.1 on 2022-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0009_typical_block_enable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typical_block',
            name='enable_for',
            field=models.CharField(choices=[('all', 'Для всех'), ('client', 'Только для клиентов'), ('expartner', 'Только для неактивных партнеров'), ('active', 'Только для активных партнеров'), ('admin', 'Только для админов')], default='all', max_length=10, verbose_name='Контент для'),
        ),
    ]
