# Generated by Django 4.0.1 on 2022-03-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0014_alter_bot_config_options_alter_partner_options_and_more'),
        ('bot_logic', '0010_alter_typical_block_enable_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('msg_text', models.TextField(verbose_name='')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.bot_config', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webhook.user', verbose_name='')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'История сообщений',
            },
        ),
    ]
