# Generated by Django 4.0.1 on 2022-03-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0022_alter_keyboard_options_alter_keyboard_button_options_and_more'),
        ('bot_logic', '0011_message_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('caption', models.CharField(max_length=50, verbose_name='Назавание блока')),
                ('block_id', models.CharField(max_length=50, unique=True, verbose_name='ID блока')),
                ('text', models.TextField(verbose_name='Содержание сообщения')),
                ('input_data', models.BooleanField(default=False, verbose_name='Фиксировать введённые данные?')),
                ('from_button', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard_button', verbose_name='По какой кнопке появиться')),
                ('kb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard', verbose_name='Клавиатура')),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_logic.client_way')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.state', verbose_name='Штатная позиция')),
            ],
            options={
                'verbose_name': 'Сообщение из автоворонки',
                'verbose_name_plural': 'Автоворонки',
            },
        ),
    ]
