# Generated by Django 4.0.1 on 2022-03-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0012_client_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_way',
            name='input_data',
            field=models.BooleanField(default=False, verbose_name='Последный вопрос (Отправить собранные данные)'),
        ),
    ]
