# Generated by Django 4.0.1 on 2022-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0013_alter_client_way_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_way',
            name='input_data',
            field=models.BooleanField(default=False, verbose_name='Отправить собранные собранные данные'),
        ),
    ]
