# Generated by Django 4.0.1 on 2022-03-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0021_alter_usr_profile_data_invest_value'),
        ('bot_logic', '0014_alter_client_way_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webhook.user', verbose_name=''),
        ),
    ]
