# Generated by Django 4.0.1 on 2022-04-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0028_remove_usergroup_buttons_usergroup_buttons_and_more'),
        ('bot_logic', '0015_alter_message_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Рассылка создана')),
                ('sending_list', models.CharField(max_length=250, verbose_name='Списки для рассылок')),
                ('sending_time', models.DateTimeField(verbose_name='Время рассылки')),
                ('sending_text', models.TextField(verbose_name='Текст рассылки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webhook.user', verbose_name='Создатель рассылки')),
            ],
        ),
    ]
