# Generated by Django 4.0.1 on 2022-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0016_sendings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendings',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='sendings',
            name='send_done',
            field=models.BooleanField(default=False, verbose_name='Рассылка исполнена'),
        ),
    ]
