# Generated by Django 4.0.1 on 2022-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0017_alter_sendings_options_sendings_send_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendings',
            name='report',
            field=models.TextField(default='', verbose_name='Отчёт по произведённой рассылке'),
        ),
    ]
