# Generated by Django 3.2.12 on 2022-04-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0024_alter_keyboard_buttons'),
        ('bot_logic', '0018_sendings_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_way',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_content.state', verbose_name='Штатная позиция'),
        ),
    ]
