# Generated by Django 3.2.12 on 2022-04-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0019_alter_client_way_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_way',
            name='delay_before',
            field=models.IntegerField(default=0, verbose_name='Задержка перед отправкой'),
        ),
        migrations.AddField(
            model_name='typical_block',
            name='delay_before',
            field=models.IntegerField(default=0, verbose_name='Задержка перед отправкой'),
        ),
    ]
