# Generated by Django 4.0.1 on 2022-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='start_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('hello_message', models.CharField(default='', max_length=500, verbose_name='Приветственное сообщение (500 символов)')),
                ('get_user_name', models.CharField(default='', max_length=500, verbose_name='Предложение познакомиться и запрос имени (500 символов)')),
                ('data_access_error', models.CharField(default='', max_length=500, verbose_name='Текст при ошибке доступа к базе пользователей (500 символов)')),
                ('name_verify_welcome', models.CharField(default='', max_length=500, verbose_name='Проверка имени при повторном использовании команды "start" зарегистрированного пользователя (500 символов)')),
                ('wrong_chat_message', models.CharField(default='', max_length=150, verbose_name='Сообщение, если команда "start" написана в общем чате (150 символов)')),
            ],
        ),
    ]
