# Generated by Django 4.0.1 on 2022-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_content',
            name='data_access_error',
            field=models.TextField(default='', verbose_name='Текст при ошибке доступа к базе пользователей'),
        ),
        migrations.AlterField(
            model_name='start_content',
            name='get_user_name',
            field=models.TextField(default='', verbose_name='Предложение познакомиться и запрос имени'),
        ),
        migrations.AlterField(
            model_name='start_content',
            name='hello_message',
            field=models.TextField(default='', verbose_name='Приветственное сообщение'),
        ),
        migrations.AlterField(
            model_name='start_content',
            name='name_verify_welcome',
            field=models.TextField(default='', verbose_name='Проверка имени при повторном использовании команды "start" зарегистрированного пользователя'),
        ),
        migrations.AlterField(
            model_name='start_content',
            name='wrong_chat_message',
            field=models.TextField(default='', verbose_name='Сообщение, если команда "start" написана в общем чате'),
        ),
    ]
