# Generated by Django 4.0.1 on 2022-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0003_start_content_new_name_please_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyboard_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
            ],
        ),
        migrations.CreateModel(
            name='keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name', models.CharField(max_length=50, verbose_name='Имя переменной клавиатуры')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('buttons', models.ManyToManyField(to='bot_content.keyboard_button', verbose_name='Кнопки')),
            ],
        ),
    ]
