# Generated by Django 4.0.1 on 2022-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0005_keyboard_button_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50, verbose_name='Назнание для ссылки (отображаться не будет)')),
                ('social', models.CharField(choices=[('YT', 'YouTube'), ('VK', 'Vkontakte'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('TG', 'Telegram'), ('DC', 'Discord'), ('TK', 'TikTok'), ('VB', 'Viber')], max_length=5, verbose_name='Площадка')),
                ('link_url', models.CharField(max_length=250, verbose_name='Ссылка на канал/профиль')),
            ],
        ),
        migrations.CreateModel(
            name='links_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Наименование группы ссылок')),
                ('permition_class', models.IntegerField(choices=[(0, 'Open for all'), (1, 'Partners ever'), (2, 'Active status only'), (3, 'Top only'), (4, 'Admins only')], default=0, verbose_name='Уровень доступа')),
                ('links', models.ManyToManyField(to='bot_content.social_link', verbose_name='Ссылки (можно выбрать несколько)')),
            ],
        ),
    ]
