# Generated by Django 4.0.1 on 2022-02-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0006_social_link_links_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_link',
            name='social',
            field=models.CharField(choices=[('YT', 'YouTube'), ('VK', 'Vkontakte'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('TG', 'Telegram'), ('DC', 'Discord'), ('TK', 'TikTok'), ('VB', 'Viber'), ('ST', 'Site')], max_length=5, verbose_name='Площадка'),
        ),
    ]
