# Generated by Django 4.0.1 on 2022-02-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0007_alter_social_link_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_menu_reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('follow_us', models.TextField(default='', verbose_name='Сообщение перед ссылками на соцсети')),
                ('rsi_detail', models.TextField(default='', verbose_name='Подробнее о RSI')),
                ('start_business', models.TextField(default='', verbose_name='Стать партнером RSI')),
                ('more', models.TextField(default='', verbose_name='Варианты заработка с RSI (продукты)')),
                ('lk', models.TextField(default='', verbose_name='Личный кабинет')),
            ],
        ),
    ]
