# Generated by Django 4.0.1 on 2022-02-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0008_main_menu_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('text', models.CharField(max_length=50, verbose_name='Текст команды')),
                ('go_to_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.keyboard', verbose_name='Переход к меню')),
            ],
        ),
    ]
