# Generated by Django 4.0.1 on 2022-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0010_state_typical_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='typical_block',
            name='text',
            field=models.TextField(default='text', verbose_name='Содержание сообщения'),
            preserve_default=False,
        ),
    ]
