# Generated by Django 4.0.1 on 2022-02-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0011_typical_block_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='typical_block',
            name='language',
            field=models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода'),
        ),
    ]
