# Generated by Django 4.0.1 on 2022-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0012_typical_block_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard_button',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Номер строки размещения кнопки'),
        ),
    ]
