# Generated by Django 4.0.1 on 2022-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0013_alter_keyboard_button_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID позиции'),
        ),
        migrations.AlterField(
            model_name='typical_block',
            name='block_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID блока'),
        ),
    ]
