# Generated by Django 4.0.1 on 2022-02-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0014_alter_state_state_id_alter_typical_block_block_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typical_block',
        ),
    ]
