# Generated by Django 4.0.1 on 2022-02-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0015_delete_typical_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text_commands',
        ),
    ]
