# Generated by Django 4.0.1 on 2022-02-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_usergroup'),
        ('bot_content', '0017_remove_main_menu_reaction_start_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard_button',
            name='another',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='webhook.usergroup', verbose_name=''),
        ),
        migrations.AddField(
            model_name='keyboard_button',
            name='visibls_for',
            field=models.CharField(choices=[('all', 'Для всех'), ('client', 'Только для клиентов'), ('partner', 'Только для партнеров'), ('admin', 'Только для админов'), ('other', 'Для другой группы')], default='all', max_length=10, verbose_name=''),
        ),
    ]
