# Generated by Django 4.0.1 on 2022-03-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0021_alter_keyboard_button_visibls_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyboard',
            options={'verbose_name': 'Клавиатура', 'verbose_name_plural': 'Клавиатуры'},
        ),
        migrations.AlterModelOptions(
            name='keyboard_button',
            options={'verbose_name': 'Кнопка клавиатуры', 'verbose_name_plural': 'Кнопки для клавиатур'},
        ),
        migrations.AlterModelOptions(
            name='links_group',
            options={'verbose_name': 'Группа ссылок', 'verbose_name_plural': 'Группы ссылок'},
        ),
        migrations.AlterModelOptions(
            name='main_menu_reaction',
            options={'verbose_name': 'Ответ на кнопки главного меню', 'verbose_name_plural': 'Ответ на кнопки главного меню'},
        ),
        migrations.AlterModelOptions(
            name='social_link',
            options={'verbose_name': 'Ссылка на соцсеть', 'verbose_name_plural': 'Ссылки на соцсети'},
        ),
        migrations.AlterModelOptions(
            name='start_content',
            options={'verbose_name': 'Содержание первых сообщений от бота', 'verbose_name_plural': 'Содержание первых сообщений от бота'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Состояние бота', 'verbose_name_plural': 'Состояния бота для пользователя'},
        ),
    ]
