# Generated by Django 4.0.1 on 2022-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_content', '0023_remove_keyboard_button_another'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='buttons',
            field=models.ManyToManyField(related_query_name='keyboard', to='bot_content.keyboard_button', verbose_name='Кнопки'),
        ),
    ]
