# Generated by Django 4.0.4 on 2022-05-22 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_ID', models.CharField(max_length=15, verbose_name='Телеграм ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя')),
                ('tg_nickname', models.CharField(max_length=50, verbose_name='Nickname в телеграм')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Адрес электронной почты')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Дата касания')),
                ('parent_ref_code', models.CharField(default='', editable=False, max_length=50, verbose_name='Родительский рефкод')),
                ('ping_stat', models.BooleanField(default=True, verbose_name='Доступность')),
                ('ref_code', models.CharField(default='markschool', editable=False, max_length=10, unique=True, verbose_name='Реферальный код')),
            ],
            options={
                'verbose_name': 'Собеседник',
                'verbose_name_plural': 'Собеседники',
            },
        ),
    ]
