# Generated by Django 4.0.5 on 2022-06-14 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=15, unique=True, verbose_name='ID')),
                ('tg_ID', models.CharField(max_length=15, verbose_name='Телеграм ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя')),
                ('tg_nickname', models.CharField(max_length=50, verbose_name='Nickname в телеграм')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Адрес электронной почты')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Дата касания')),
                ('parent_ref_code', models.CharField(default='', editable=False, max_length=50, verbose_name='Родительский рефкод')),
                ('ping_stat', models.BooleanField(default=True, verbose_name='Доступность')),
                ('ref_code', models.CharField(default='markschool', editable=False, max_length=10, unique=True, verbose_name='Реферальный код')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота')),
            ],
            options={
                'verbose_name': 'Собеседник',
                'verbose_name_plural': 'Собеседники',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=15, unique=True, verbose_name='Tag ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('description', models.TextField(verbose_name='Описание тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Переменная (латиницей)')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_assets.user', verbose_name='Собеседник')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Users_assets.usertag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('date', models.DateTimeField(verbose_name='Время активации')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Users_assets.user', verbose_name='Активировал')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Users_assets.user', verbose_name='Пригласил')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
    ]
