# Generated by Django 4.0.4 on 2022-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=15, verbose_name='Tag ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('description', models.TextField(verbose_name='Описание тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
