# Generated by Django 4.0.5 on 2022-06-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('Users_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота'),
        ),
    ]
