# Generated by Django 4.0.5 on 2022-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0002_usertag_from_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_ID',
            field=models.CharField(max_length=25, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='Tag ID'),
        ),
    ]
