# Generated by Django 4.0.4 on 2022-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0002_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='Users_assets.usertag', verbose_name='Теги'),
        ),
    ]
