# Generated by Django 4.0.4 on 2022-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0003_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_ID',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='Tag ID'),
        ),
    ]
