# Generated by Django 4.0.4 on 2022-05-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgbot_active'),
        ('Users_assets', '0006_alter_user_from_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Через бота'),
        ),
    ]
