# Generated by Django 4.0.4 on 2022-05-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0010_user_user_id_alter_user_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('date', models.DateTimeField(verbose_name='Время активации')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Users_assets.user', verbose_name='Активировал')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Users_assets.user', verbose_name='Пригласил')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
    ]
