# Generated by Django 4.0.4 on 2022-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0011_reflink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.CharField(max_length=15, unique=True, verbose_name='ID'),
        ),
    ]
