# Generated by Django 4.0.4 on 2022-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0012_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Users_assets.usertag', verbose_name='Теги'),
        ),
    ]
