# Generated by Django 4.0.5 on 2022-06-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('Users_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('var_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Переменная')),
                ('qual', models.CharField(choices=[('=', 'РАВНО'), ('>=', 'БОЛЬШЕ-РАВНО'), ('>', 'БОЛЬШЕ'), ('<=', 'МЕНЬШЕ-РАВНО'), ('<', 'МЕНЬШЕ')], default='=', max_length=2, verbose_name='Сравнение')),
                ('var_value', models.CharField(blank=True, max_length=150, null=True, verbose_name='Значение')),
                ('failed_text', models.TextField(blank=True, null=True, verbose_name='Текст при неудаче')),
                ('usr_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users_assets.usertag', verbose_name='ИЛИ по тегу')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя переменной клавиатуры')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
            ],
            options={
                'verbose_name': 'Клавиатура',
                'verbose_name_plural': 'Клавиатуры',
            },
        ),
        migrations.CreateModel(
            name='keyboard_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('order', models.IntegerField(default=1, verbose_name='Номер строки размещения кнопки')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='bot', to='core.tgbot', verbose_name='Через бота')),
            ],
            options={
                'verbose_name': 'Кнопка клавиатуры',
                'verbose_name_plural': 'Кнопки для клавиатур',
            },
        ),
        migrations.CreateModel(
            name='TypeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст реакции')),
                ('input_state', models.BooleanField(default=False, verbose_name='Ожидание ввода?')),
                ('save_to_var', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя переменной для сохранения ввода')),
                ('value_to_save', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Значение переменной (если ввод не ожидается)')),
                ('delay', models.IntegerField(default=0, verbose_name='Задержка перед реакцией (секунды)')),
                ('conditions', models.ManyToManyField(blank=True, to='Content_and_logic.condition', verbose_name='Условия')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота')),
                ('from_button', models.ManyToManyField(blank=True, to='Content_and_logic.keyboard_button', verbose_name='По кнопке')),
                ('keyboard', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.keyboard', verbose_name='Клавиатура')),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок')),
            ],
            options={
                'verbose_name': 'Типовой блок',
                'verbose_name_plural': 'Типовые блоки (сообщения от бота)',
            },
        ),
        migrations.AddField(
            model_name='keyboard',
            name='buttons',
            field=models.ManyToManyField(related_query_name='keyboard', to='Content_and_logic.keyboard_button', verbose_name='Кнопки'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='bot', to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.CreateModel(
            name='FirstTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст реакции')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tgbot', verbose_name='Через бота')),
                ('keyboard', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.keyboard', verbose_name='Клавиатура')),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок')),
            ],
            options={
                'verbose_name': 'Первое касание',
                'verbose_name_plural': 'Первые касания',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Команда (латиницей)')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст реакции')),
                ('delay', models.IntegerField(default=0, verbose_name='Задержка перед реакцией (секунды)')),
                ('conditions', models.ManyToManyField(blank=True, to='Content_and_logic.condition', verbose_name='Условия')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота')),
                ('keyboard', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.keyboard', verbose_name='Клавиатура')),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
