# Generated by Django 4.0.4 on 2022-05-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyboard_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('order', models.IntegerField(default=1, verbose_name='Номер строки размещения кнопки')),
            ],
            options={
                'verbose_name': 'Кнопка клавиатуры',
                'verbose_name_plural': 'Кнопки для клавиатур',
            },
        ),
        migrations.CreateModel(
            name='keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name', models.CharField(max_length=50, verbose_name='Имя переменной клавиатуры')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('buttons', models.ManyToManyField(related_query_name='keyboard', to='Content_and_logic.keyboard_button', verbose_name='Кнопки')),
            ],
            options={
                'verbose_name': 'Клавиатура',
                'verbose_name_plural': 'Клавиатуры',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=10, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Команда')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода')),
                ('text', models.TextField(verbose_name='Текст реакции')),
                ('delay', models.IntegerField(verbose_name='Задержка перед реакцией')),
                ('keyboard', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Content_and_logic.keyboard', verbose_name='Клавиатура')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
