# Generated by Django 4.0.4 on 2022-05-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgbot_active'),
        ('Content_and_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='from_bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='from_bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AddField(
            model_name='keyboard_button',
            name='from_bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AddField(
            model_name='keyboard_button',
            name='language',
            field=models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'English'), ('TUR', 'Turkish'), ('GER', 'German'), ('FR', 'Frankish')], default='RUS', max_length=5, verbose_name='Язык перевода'),
        ),
    ]
