# Generated by Django 4.0.5 on 2022-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0002_usertag_from_bot'),
        ('Content_and_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeblock',
            name='add_tag',
            field=models.ManyToManyField(blank=True, related_name='add_tag', to='Users_assets.usertag', verbose_name='Добавить тэг'),
        ),
        migrations.AddField(
            model_name='typeblock',
            name='remove_tag',
            field=models.ManyToManyField(blank=True, related_name='remove_tag', to='Users_assets.usertag', verbose_name='Удалить тэг'),
        ),
    ]
