# Generated by Django 4.0.5 on 2022-06-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0002_usertag_from_bot'),
        ('Content_and_logic', '0002_typeblock_add_tag_typeblock_remove_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeblock',
            name='add_tag',
            field=models.ManyToManyField(blank=True, limit_choices_to={'from_bot': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота')}, related_name='add_tag', to='Users_assets.usertag', verbose_name='Добавить тэг'),
        ),
    ]
