# Generated by Django 4.0.4 on 2022-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0002_command_from_bot_keyboard_from_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID'),
        ),
    ]
