# Generated by Django 4.0.4 on 2022-05-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0003_alter_command_command_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя переменной клавиатуры'),
        ),
        migrations.AlterField(
            model_name='keyboard_button',
            name='caption',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
