# Generated by Django 4.0.5 on 2022-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0003_alter_user_tg_id_alter_usertag_tag_id'),
        ('Content_and_logic', '0003_alter_typeblock_add_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typeblock',
            name='add_tag',
            field=models.ManyToManyField(blank=True, related_name='add_tag', to='Users_assets.usertag', verbose_name='Добавить тэг'),
        ),
    ]
