# Generated by Django 4.0.4 on 2022-05-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgbot_active'),
        ('Content_and_logic', '0004_alter_keyboard_name_alter_keyboard_button_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='caption',
            field=models.CharField(max_length=50, verbose_name='Команда (латиницей)'),
        ),
        migrations.AlterField(
            model_name='command',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Задержка перед реакцией (секунды)'),
        ),
        migrations.AlterField(
            model_name='command',
            name='from_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AlterField(
            model_name='command',
            name='keyboard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Content_and_logic.keyboard', verbose_name='Клавиатура'),
        ),
    ]
