# Generated by Django 4.0.4 on 2022-05-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgbot_active'),
        ('Content_and_logic', '0007_alter_keyboard_from_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота'),
        ),
        migrations.AlterField(
            model_name='keyboard_button',
            name='from_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tgbot', verbose_name='Через бота'),
        ),
    ]
