# Generated by Django 4.0.4 on 2022-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0010_alter_keyboard_from_bot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('var_key', models.CharField(max_length=50, verbose_name='Переменная')),
                ('var_value', models.CharField(max_length=150, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='input_state',
            field=models.BooleanField(default=False, verbose_name='Ожидание ввода?'),
        ),
        migrations.AddField(
            model_name='command',
            name='next_block',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Следующий блок'),
        ),
        migrations.AddField(
            model_name='command',
            name='conditions',
            field=models.ManyToManyField(blank=True, null=True, to='Content_and_logic.condition', verbose_name='Условия'),
        ),
    ]
