# Generated by Django 4.0.4 on 2022-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0011_condition_command_input_state_command_next_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='qual',
            field=models.CharField(choices=[('=', 'РАВНО'), ('>=', 'БОЛЬШЕ-РАВНО'), ('>', 'БОЛЬШЕ'), ('<=', 'МЕНЬШЕ-РАВНО'), ('<', 'МЕНЬШЕ')], default='=', max_length=2, verbose_name='Сравнение'),
        ),
    ]
