# Generated by Django 4.0.4 on 2022-05-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_assets', '0012_alter_user_user_id'),
        ('Content_and_logic', '0012_condition_qual'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='usr_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users_assets.usertag', verbose_name='ИЛИ по тегу'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='var_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Переменная'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='var_value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Значение'),
        ),
    ]
