# Generated by Django 4.0.4 on 2022-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0013_condition_usr_tag_alter_condition_var_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='failed_text',
            field=models.TextField(default=2, verbose_name='Текст при неудаче'),
            preserve_default=False,
        ),
    ]
