# Generated by Django 4.0.4 on 2022-05-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0017_typeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок'),
        ),
        migrations.AlterField(
            model_name='typeblock',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок'),
        ),
    ]
