# Generated by Django 4.0.4 on 2022-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0018_alter_command_next_block_alter_typeblock_next_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='input_state',
        ),
        migrations.AddField(
            model_name='typeblock',
            name='save_to_var',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Имя переменной для сохранения ввода'),
        ),
    ]
