# Generated by Django 4.0.4 on 2022-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0021_delete_funcblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeblock',
            name='value_to_save',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Значение переменной (если ввод не ожидается)'),
        ),
    ]
