# Generated by Django 4.0.5 on 2022-06-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0022_typeblock_value_to_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttouch',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Content_and_logic.typeblock', verbose_name='Следующий блок'),
        ),
    ]
