# Generated by Django 4.0.5 on 2022-06-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content_and_logic', '0023_alter_firsttouch_next_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsttouch',
            name='input_state',
        ),
    ]
